controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_1_joint
      - left_finger_2_joint
      - left_finger_3_joint
      - middle_finger_2_joint
      - middle_finger_3_joint
      - right_finger_2_joint
      - right_finger_3_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: ready
  - group: gripper
    pose: ready