joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_finger_1_joint
      - left_finger_2_joint
      - left_finger_3_joint
      - middle_finger_2_joint
      - middle_finger_3_joint
      - right_finger_2_joint
      - right_finger_3_joint




joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
    constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.5
    stop_trajectory_duration: 1.0
    state_publish_rate:  25
    action_monitor_rate: 25
    gains:
        joint_1: {p: 3000.0, i: 0.0, d: 2.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
        joint_2: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -5.0, i_clamp_max: 5.0}
        joint_3: {p: 30000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_4: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_5: {p: 750.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_6: {p: 50000.0, i: 0.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_7: {p: 3000.0, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1}
  
# joint_1_position_controller:
#     joint: joint_1
#     pid:
#         p: 3000.0
#         i: 0.0
#         d: 2.0
#     type: effort_controllers/JointPositionController

# joint_2_position_controller:
#     joint: joint_2
#     pid:
#         p: 50000.0
#         i: 0.0
#         d: 0.0
#     type: effort_controllers/JointPositionController

# joint_3_position_controller:
#     joint: joint_3
#     pid:
#         p: 3000.0
#         i: 0.0
#         d: 0.0
#     type: effort_controllers/JointPositionController

# joint_4_position_controller:
#     joint: joint_4
#     pid:
#         p: 50000.0
#         i: 0.0
#         d: 0.0
#     type: effort_controllers/JointPositionController

# joint_5_position_controller:
#     joint: joint_5
#     pid:
#         p: 3000.0
#         i: 0.0
#         d: 0.2
#     type: effort_controllers/JointPositionController

# joint_6_position_controller:
#     joint: joint_6
#     pid:
#         p: 50000.0
#         i: 0.0
#         d: 1
#     type: effort_controllers/JointPositionController

# joint_7_position_controller:
#     joint: joint_7
#     pid:
#         p: 1000.0
#         i: 0.0
#         d: 0.0
#     type: effort_controllers/JointPositionController


gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger_1_joint
    - left_finger_2_joint
    - left_finger_3_joint
    - middle_finger_2_joint
    - middle_finger_3_joint
    - right_finger_2_joint
    - right_finger_3_joint
  gains:
    left_finger_1_joint:
      p: 140
      d: 0.01
      i: 0
      i_clamp: 1
    left_finger_2_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    left_finger_3_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    middle_finger_2_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    middle_finger_3_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    right_finger_2_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    right_finger_3_joint:
      p: 140
      d: 0
      i: 0
      i_clamp: 1
    right_finger_1_joint:
      p: 140
      d: 0.01
      i: 0
      i_clamp: 1


# gazebo_ros_control:
#   pid_gains:
#         right_finger_1_joint: {p: 10.0, i: 0.0, d: 0.01}