controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_finger_1_joint
      - left_finger_2_joint
      - left_finger_3_joint
      - middle_finger_2_joint
      - middle_finger_3_joint
      - right_finger_2_joint
      - right_finger_3_joint